---
- name: add ssh keys
  authorized_key:
          user: awireman
          state: present
          key: "{{ lookup ('file', '/home/awireman/.ssh/id_rsa.pub') }}"

- file: path=/home/awireman/.ssh state=directory owner=awireman mode=0700
- file: path=/home/awireman/.ssh/authorized_keys state=file owner=awireman mode=0600

- name: install ubuntu packages
  become: true
  apt: name={{item}} state=present
  with_items:
        - nfs-common
        - git
  tags: [ 'packages' ]

- name: sign into git
  shell: git config --global user.name {{ git_user }}
  shell: git config --global user.email {{ git_email }}

- name: mount drives
  become: true
  shell: mdkir -p /mnt/pool
  shell: if [ -z $(grep {{ nfs_string }} /etc/fstab) ]; then echo {{ nfs_string }} >> /etc/fstab; fi
  notify: restart

- name: fix ssh config
  become: true
  shell: sed -i -e 's/{{ old_ssh_string }}/{{ new_ssh_string }}/g' /etc/ssh/sshd_config
