---
- name: install docker
  apt: name={{item}} state=present
  with_items:
        - docker.io
  notify: restart
  tags: [ 'packages' ]

- name: ensure docker is started and enabled
  service: name=docker state=started enabled=yes
  tags: [ 'service' ]

- name: add user to docker group
  become: true
  shell: gpasswd -a {{ ansible_user }} docker
