---
- name: remove old docker
  apt: name={{item}} state=absent
  with_items:
          - docker
          - docker-engine
          - docker.io
  tags: ['firstInstall']

- name: install docker
  apt: name={{item}} state=present
  with_items:
        - docker.io
  tags: [ 'packages' ]

- name: ensure docker is started and enabled
  service: name=docker state=started enabled=yes
  tags: [ 'service' ]
