---
- name: install docker
  apt: name={{item}} state=present
  with_items:
        - docker.io
  tags: [ 'packages' ]

- name: ensure docker is started and enabled
  service: name=docker state=started enabled=yes
  tags: [ 'service' ]
